### ISSUE TITLE
Official Barman download for PG 13 on CentOS missing

### ISSUE THREAD

**Issue by justinclift** [EnterpriseDB/barman#331]
Just went to install Barman on a CentOS test instance running PG 13, then noticed there's no "PostgreSQL 13" option on the download page:

&nbsp; &nbsp; https://dl.2ndquadrant.com/default/release/site/#rpm

The script for grabbing the PG 13 version of Barman [*is* there](https://dl.2ndquadrant.com/default/release/get/13/rpm) though, so this looks to just be an oversight in adding a new button to the download page when PG 13 was released. :wink:

**NOTE** - Hoping this is an ok place to report this, as I'm not sure what the "correct" place is to report stuff for https://dl.2ndquadrant.com.

**Comment by justinclift** [comment]
Hmmm, there aren't any packages for Barman in the repo it gives:

&nbsp; &nbsp; https://dl.2ndquadrant.com/default/release/browse/rpm/packages/rhel/7Server/x86_64/13/

Should the package from EPEL or PGDG be used instead?  (either way, Barman docs will probably need updating)

**Comment by amenonsen** [comment]
This has been fixed quite some time ago.

**Comment by justinclift** [comment]
Hmmm, when I go to the page right now, it's still not there:

https://dl.2ndquadrant.com/default/release/site/#rpm

The highest version with a button there, is PostgreSQL 12.

**Comment by amenonsen** [comment]
Oh, you're right. I'll get someone to look at that.

However, there now are (and will continue to be, for new releases) Barman packages under the original URL you posted: https://dl.2ndquadrant.com/default/release/browse/rpm/packages/rhel/7Server/x86_64/13/
